# https://github.com/marketplace/pr-label-enforcer
version: '1'
invalidStatus: "pending"
labelRule:
  startsWith:
    - "Semver:"
  values:
    - "Type: Breaking Change"
    - "Type: Feature"
    - "Type: Bug"
