name: Publish-Binary
on: push

publish-binary:
  runs-on: ${{ matrix.os }}
  if: startsWith(github.ref, 'refs/tags/')
  strategy:
    matrix:
      os: [macOS-latest, windows-latest, ubuntu-18.04]
      node_version: [12.9.1] # pre-build nexe https://github.com/nexe/nexe/releases/tag/v3.0.0
  steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install
      run: npm install # avoid hoisting https://github.com/nexe/nexe/issues/649
      working-directory: ./publish/binary-compiler
    - name: Build binary
      run: npm run dist
      working-directory: ./publish/binary-compiler
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}
        path: ./publish/binary-compiler/dist
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: "./publish/binary-compiler/dist/**"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
