# Post publish after npm
name: Publish-Artifact
on:
  workflow_run:
    workflows:
      - publish
    branches:
      - main
    types:
      - completed
env:
  DOCKER_BASE_NAME: docker.pkg.github.com/${{ github.repository }}/secretlint
  DOCKER_HUB_BASE_NAME: secretlint/secretlint

permissions:
  contents: write
  packages: write
jobs:
  # npm binary
  publish-binary:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-18.04]
        node-version: [12.9.1] # pre-build nexe https://github.com/nexe/nexe/releases/tag/v3.0.0
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Define ${CURRENT_VERSION}
      - name: Set Current Version
        shell: bash -ex {0}
        run: |
          CURRENT_VERSION=$(node -p 'require("./lerna.json").version')
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
      - name: Install
        run: npm install # avoid hoisting https://github.com/nexe/nexe/issues/649
        working-directory: ./publish/binary-compiler
      - name: Build binary
        run: npm run dist
        working-directory: ./publish/binary-compiler
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: ./publish/binary-compiler/dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.CURRENT_VERSION }}
          files: "./publish/binary-compiler/dist/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Docker
  publish-docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      # Define ${CURRENT_VERSION}
      - name: Set Current Version
        shell: bash -ex {0}
        run: |
          CURRENT_VERSION=$(node -p 'require("./lerna.json").version')
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
      - name: "Set TAG_NAME=tags"
        run: |
          echo "TAG_NAME=v${{ env.CURRENT_VERSION }}" >> $GITHUB_ENV
          echo "SECRETLINT_VERSION=${{ env.CURRENT_VERSION }}" >> $GITHUB_ENV
      - name: Set HUB_TAG
        run: |
          echo "PKG_TAG=${DOCKER_BASE_NAME}:${TAG_NAME}" >> $GITHUB_ENV
          echo "PKG_LATEST_TAG=${DOCKER_BASE_NAME}:latest" >> $GITHUB_ENV
          echo "HUB_TAG=${DOCKER_HUB_BASE_NAME}:${TAG_NAME}" >> $GITHUB_ENV
          echo "HUB_LATEST_TAG=${DOCKER_HUB_BASE_NAME}:latest" >> $GITHUB_ENV
      - name: Build image
        run: |
          docker build . -t "${PKG_TAG}" --build-arg SECRETLINT_VERSION=${SECRETLINT_VERSION}
          docker tag "${PKG_TAG}" "${HUB_LATEST_TAG}"
          docker tag "${PKG_TAG}" "${HUB_TAG}"
        working-directory: ./publish/docker
      - name: Print version
        run: |
          docker run --rm ${PKG_TAG} --version
        working-directory: ./publish/docker
      - name: Login to Registries
        run: |
          echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u azu --password-stdin
          echo "${DOCKER_HUB_TOKEN}" | docker login -u efcl --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Push to GitHub Packages
        run: |
          docker push "${PKG_TAG}"
      - name: Push to Docker Hub
        run: |
          docker push "${HUB_TAG}"
          docker push "${HUB_LATEST_TAG}"
